spring.application.name=reportes

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATASOURCE (Railway)
# ===============================
spring.datasource.url=${DATABASE_URL}?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}

# ===============================
# MULTIPART
# ===============================
spring.servlet.multipart.max-file-size=700MB
spring.servlet.multipart.max-request-size=700MB

# ===============================
# SPRING BATCH
# ===============================
spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false
