spring.application.name=reportes

spring.application.name=reportes


# ===============================
# DATASOURCE (Railway)
# ===============================
#spring.datasource.url=${DATABASE_URL}?sslmode=require
#spring.datasource.url=jdbc:postgresql://switchyard.proxy.rlwy.net:10409/railway
#spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/${PGDATABASE}
spring.datasource.url=jdbc:postgresql://${HOST}:${PORT}/${DATABASE}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}

#spring.datasource.url=jdbc:postgresql://localhost:5433/prueba
#spring.datasource.username=postgres
#spring.datasource.password=conejoej7
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
#jwt.secret=a018d6e280fdb380c4c7a11ba8797fdcf2f10aacba6c857c5a6454a53655812a07854795aea25aec250b7557ba18617e66fe65a7d66d91d7ed128adbe58eda5f9117c581f70805567ed834d06dd28a7f0ef1b7592865535f117a57cc54be70e5eb9a2fd86d2af324450077229fa746f0e4933d32b019c57ab038abc9a1a91862bf86d10bc40c0ccca413daec63a907fb97a7e29833fa8057992cfef71300554b446d2e5b2d9e228af495fb7e762ca6a70998929e9b1ba483d176a2bf17c9e4cf79148b179c6d33aeda25fdddd3405d91517efd5a04cce3cdb6beb6a15164bfbcf85f94e84e53c0e44d31368f1b3fb9c537d3acf59f5c03624589dde50a80f7f9

# ===============================
# MULTIPART
# ===============================
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# ===============================
# SPRING BATCH
# ===============================
spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false

# ===============================
# SERVER
# ===============================
server.port=${PORT}

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
spring.batch.jdbc.initialize-schema=never
spring.jpa.properties.hibernate.jdbc.time_zone=America/Guayaquil
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

#logging.level.org.springframework.boot.autoconfigure=DEBUG

#server.port=8097
