spring.application.name=reportes

# ===============================
# SERVER
# ===============================
server.port=${SPORT:8080}

# ===============================
# DATASOURCE (Railway)
# ===============================
#spring.datasource.url=${DATABASE_URL}?sslmode=require
#spring.datasource.url=jdbc:postgresql://switchyard.proxy.rlwy.net:10409/railway
spring.datasource.url=jdbc:postgresql://${HOST}:${PORT}/${DATABASE}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}

# ===============================
# MULTIPART
# ===============================
spring.servlet.multipart.max-file-size=700MB
spring.servlet.multipart.max-request-size=700MB

# ===============================
# SPRING BATCH
# ===============================
spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false
